# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 01:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0002_auto_20190225_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class_model_model1',
            name='SystemID',
            field=models.CharField(max_length=60),
        ),
    ]
