# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0006_auto_20190225_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_model_model1',
            old_name='free_memory',
            new_name='alive',
        ),
        migrations.RenameField(
            model_name='class_model_model1',
            old_name='systemID',
            new_name='router_name',
        ),
        migrations.RemoveField(
            model_name='class_model_model1',
            name='total_memory',
        ),
        migrations.RemoveField(
            model_name='class_model_model1',
            name='uptime',
        ),
    ]
