# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 17:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_auto_20190225_2317'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_model_model1',
            name='alive',
        ),
    ]
