# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 18:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_remove_class_model_model1_alive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class_model_model1',
            name='licenselevel',
        ),
    ]
