# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0009_remove_class_model_model1_licenselevel'),
    ]

    operations = [
        migrations.AddField(
            model_name='class_model_model1',
            name='ailve',
            field=models.CharField(default=1, max_length=60),
            preserve_default=False,
        ),
    ]
