# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-25 20:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0010_class_model_model1_ailve'),
    ]

    operations = [
        migrations.RenameField(
            model_name='class_model_model1',
            old_name='ailve',
            new_name='alive',
        ),
    ]
